"""migrate to postgresql

Revision ID: 75452a3c1d99
Revises: 85f1f2dbac61
Create Date: 2026-04-10 16:29:48.679865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75452a3c1d99'
down_revision: Union[str, Sequence[str], None] = '85f1f2dbac61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'revoked_tokens' not in existing_tables:
        op.create_table('revoked_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('token_hash', sa.String(length=64), nullable=False),
        sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
        op.create_index(op.f('ix_revoked_tokens_token_hash'), 'revoked_tokens', ['token_hash'], unique=True)
    op.alter_column('agency_profiles', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    existing_cols_applications = [c['name'] for c in inspector.get_columns('applications')]
    if 'applied_at' not in existing_cols_applications:
        op.add_column('applications', sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True))
    existing_cols_job_listings = [c['name'] for c in inspector.get_columns('job_listings')]
    if 'company_id' not in existing_cols_job_listings:
        op.add_column('job_listings', sa.Column('company_id', sa.Integer(), nullable=True))
    if 'agency_id' not in existing_cols_job_listings:
        op.add_column('job_listings', sa.Column('agency_id', sa.Integer(), nullable=True))
    if 'company_name' not in existing_cols_job_listings:
        op.add_column('job_listings', sa.Column('company_name', sa.String(), nullable=True))
    if 'pay_per_delivery' not in existing_cols_job_listings:
        op.add_column('job_listings', sa.Column('pay_per_delivery', sa.String(), nullable=True))
    op.alter_column('job_listings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('job_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('job_listings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('job_listings', 'pay_per_delivery')
    op.drop_column('job_listings', 'company_name')
    op.drop_column('job_listings', 'agency_id')
    op.drop_column('job_listings', 'company_id')
    _bind = op.get_bind()
    _inspector = sa.inspect(_bind)
    _existing_cols = [c['name'] for c in _inspector.get_columns('applications')]
    if 'applied_at' in _existing_cols:
        op.drop_column('applications', 'applied_at')
    op.alter_column('agency_profiles', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'revoked_tokens' in existing_tables:
        op.drop_index(op.f('ix_revoked_tokens_token_hash'), table_name='revoked_tokens')
        op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
        op.drop_table('revoked_tokens')
    # ### end Alembic commands ###