"""auto update

Revision ID: 9821e197a92f
Revises: 
Create Date: 2026-03-21 07:16:22.106624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9821e197a92f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'agency_profiles' not in existing_tables:
        op.create_table('agency_profiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('manager_name', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('district', sa.String(), nullable=True),
        sa.Column('platform', sa.String(), nullable=True),
        sa.Column('pay_per_delivery', sa.String(), nullable=True),
        sa.Column('promotion', sa.String(), nullable=True),
        sa.Column('settlement_type', sa.String(), nullable=True),
        sa.Column('motorcycle_option', sa.String(), nullable=True),
        sa.Column('work_type', sa.String(), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_agency_profiles_id'), 'agency_profiles', ['id'], unique=False)

    if 'applications' not in existing_tables:
        op.create_table('applications',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('job_listing_id', sa.Integer(), nullable=True),
        sa.Column('agency_name', sa.String(), nullable=True),
        sa.Column('rider_name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)

    if 'consultations' not in existing_tables:
        op.create_table('consultations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('agency', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)

    if 'job_listings' not in existing_tables:
        op.create_table('job_listings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('agency_name', sa.String(), nullable=True),
        sa.Column('region', sa.String(), nullable=True),
        sa.Column('sub_region', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('conditions', sa.String(), nullable=True),
        sa.Column('promotion', sa.String(), nullable=True),
        sa.Column('motorcycle', sa.String(), nullable=True),
        sa.Column('settlement', sa.String(), nullable=True),
        sa.Column('work_time', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)

    if 'rider_profiles' not in existing_tables:
        op.create_table('rider_profiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('city', sa.String(), nullable=True),
        sa.Column('district', sa.String(), nullable=True),
        sa.Column('experience', sa.String(), nullable=True),
        sa.Column('has_motorcycle', sa.Boolean(), nullable=True),
        sa.Column('rider_type', sa.String(), nullable=True),
        sa.Column('birth_year', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_rider_profiles_id'), 'rider_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'rider_profiles' in existing_tables:
        op.drop_index(op.f('ix_rider_profiles_id'), table_name='rider_profiles')
        op.drop_table('rider_profiles')
    if 'job_listings' in existing_tables:
        op.drop_index(op.f('ix_job_listings_id'), table_name='job_listings')
        op.drop_table('job_listings')
    if 'consultations' in existing_tables:
        op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
        op.drop_table('consultations')
    if 'applications' in existing_tables:
        op.drop_index(op.f('ix_applications_id'), table_name='applications')
        op.drop_table('applications')
    if 'agency_profiles' in existing_tables:
        op.drop_index(op.f('ix_agency_profiles_id'), table_name='agency_profiles')
        op.drop_table('agency_profiles')
    # ### end Alembic commands ###